### ISSUE TITLE
Undefined method `method_name` in rubocop 0.59.2

### ISSUE THREAD

**Issue by JanStevens** [rubocop-hq/rubocop-performance#22]
Rubocop Performance does not work with latest rubocop 0.59.2

```
undefined method `method_name' for s(:lvar, :evaluator):RuboCop::AST::Node
Did you mean?  method
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:60:in `array?'
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:50:in `eligible_receiver?'
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:44:in `eligible_node?'
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:30:in `on_send'
```

**Comment by koic** [comment]
Thanks for trying the edge code. rubocop-performance 0.0.1 has been released.

RuboCop Performance is still work in progress, but please let me know if you noticed anything :-)
