### PR TITLE
[Fix #22] Change runtime dependency RuboCop to 0.58.0 or higher

### LINKED ISSUE #22: Undefined method `method_name` in rubocop 0.59.2
Rubocop Performance does not work with latest rubocop 0.59.2

```
undefined method `method_name' for s(:lvar, :evaluator):RuboCop::AST::Node
Did you mean?  method
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:60:in `array?'
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:50:in `eligible_receiver?'
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:44:in `eligible_node?'
/Users/fritz/.asdf/installs/ruby/2.5.1/lib/ruby/gems/2.5.0/gems/rubocop-performance-0.0.0/lib/rubocop/cop/performance/size.rb:30:in `on_send'
```

### PR DESCRIPTION
**Pull request by koic**
Fixes #22.

This PR specifies the same dependency version as rubocop-hq/rubocop-rspec#664.

### CODE REVIEW

**Comment by koic** [comment]
@bbatsov rubocop-performance is still work in progress, I'd like to release rubocop-performance 0.0.1 to solve this problem #22.

**Comment by bbatsov** [comment]
Sure! 👍
